module.exports = {
  notes: [
    {
      type: 'category',
      label: 'Linux',
      collapsed: true,
      items: [
        'linux/linux',
        'linux/suckless',
        'linux/setting-up',
        'linux/vim',
        'linux/emacs',
        'linux/tmux',
        'linux/git',
        'linux/grep',
        'linux/sed',
        'linux/awk',
        'linux/jq',
        'linux/find',
        'linux/xargs',
        'linux/fzf',
        'linux/curl',
        'linux/wget',
        'linux/ssh',
        'linux/pgp',
        'linux/rsync',
        'linux/shells',
        'linux/window-managers',
        'linux/terminal-emulators',
        'linux/text-editors-and-ides',
        'linux/browsers',
      ],
    },
    {
      type: 'category',
      label: 'Programming',
      items: [
        'programming/python',
        'programming/javascript',
        'programming/typescript',
        'programming/haskell',
        'programming/rust',
        'programming/css',
        'programming/html',
      ],
    },
    {
      type: 'category',
      label: 'Recreational mathematics',
      items: [
        'recreational-mathematics/speedcubing',
        'recreational-mathematics/mathemagics',
        'recreational-mathematics/chess',
        'recreational-mathematics/card-tricks',
        'recreational-mathematics/mathematical-constants',
        'recreational-mathematics/mnemonics',
      ],
    },
    {
      type: 'category',
      label: 'Mathematics',
      items: [
        {
          type: 'category',
          label: 'Calculus',
          items: [
            'mathematics/calculus/limits',
            'mathematics/calculus/differential-calculus',
            'mathematics/calculus/integral-calculus',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Misc',
      items: [
        'misc/websites',
        'misc/rss',
        'misc/privacy',
        'misc/poems',
        'misc/quotes',
        'misc/misc',
      ],
    },
    {
      type: 'category',
      label: 'Book notes',
      items: ['books/python-tricks'],
    },
  ],
};
